In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
preprocessor = hub.KerasLayer(
    "https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-preprocess/3")

encoder = hub.KerasLayer(
    "https://kaggle.com/models/tensorflow/bert/TensorFlow2/en-uncased-l-12-h-768-a-12/3")

In [3]:
 text = ['what a great day','sun rises from the east']

## Preprocessing Stage

In [4]:
text_preprocessed = preprocessor(text)

In [5]:
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [6]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

##### In the first sentence we can see 1,1,1,1,1,1, 6 1s because of CLS,what,a,great,day,SEP. Rest zeroes are padding, total is 128

In [7]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[ 101, 2054, 1037, 2307, 2154,  102,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 3103, 9466, 2013, 1996, 2264,  102,    0,    0,    0,    0,
           0,

##### These are unqiue ids assigned to each word in the two sentences. See, CLS and SEP have same ids in both sentences.

## Getting Vector Embeddings

In [9]:
bert_results  = encoder(text_preprocessed)

In [10]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [11]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8922907 , -0.27825385, -0.06699808, ...,  0.07035173,
        -0.6557936 ,  0.9148911 ],
       [-0.949043  , -0.46740755, -0.6000462 , ..., -0.26696098,
        -0.7178697 ,  0.94251263]], dtype=float32)>

##### pooled output is embedding for one full sentence (768 size vector for each sentence)

In [12]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.19191845,  0.21653955, -0.11859062, ..., -0.35402253,
          0.41379493,  0.04800985],
        [ 0.33743173, -0.2346995 ,  0.07392374, ..., -0.6278212 ,
          0.18043289, -0.05062849],
        [-0.7945057 , -0.5397667 , -0.25288257, ...,  0.18351826,
          0.6719551 ,  0.39567688],
        ...,
        [-0.03762557,  0.04330589,  0.47213206, ...,  0.1553379 ,
         -0.07124414,  0.00775581],
        [ 0.03599672,  0.15864244,  0.32230073, ..., -0.09132466,
         -0.2867892 ,  0.16536163],
        [-0.21696751,  0.00390628,  0.48164985, ...,  0.2987059 ,
         -0.07675894, -0.04128731]],

       [[-0.26726124,  0.22481291, -0.05429769, ..., -0.5905349 ,
          0.20184913,  0.15834296],
        [-0.05502979, -0.00592054,  0.80034447, ..., -0.2462964 ,
          0.23970072, -0.6370451 ],
        [-0.21202053,  0.496581  ,  0.33780584, ..., -0.3719287 ,
         -0.9100675 , -0.69192964],
        ...,

##### sequence coutput is embedding for each word in every sentence

In [13]:
len(bert_results['encoder_outputs'])

12

In [14]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.22012036,  0.09068702, -0.08315688, ...,  0.03400554,
           0.04797502,  0.08352929],
         [ 1.0502597 ,  0.9727412 , -1.3618356 , ...,  0.6588406 ,
          -0.08084039, -1.7533158 ],
         [ 0.49834424,  0.9011609 ,  0.6588869 , ..., -0.34464028,
           0.20952764,  0.2349733 ],
         ...,
         [-0.07988055, -0.1171667 ,  0.6506098 , ...,  0.44134408,
          -0.39226782,  0.0108016 ],
         [-0.14368975, -0.1432171 ,  0.5363914 , ...,  0.46878293,
          -0.30482504, -0.08491935],
         [-0.02785834, -0.06471311,  0.54978913, ...,  0.76856405,
          -0.5940916 , -0.1725046 ]],
 
        [[ 0.22578812,  0.08740502, -0.10014953, ..., -0.01797759,
           0.10198347,  0.18141292],
         [ 0.49430412,  1.1278975 ,  0.8109198 , ...,  0.11209655,
           0.4305913 , -0.4439959 ],
         [-0.33467978,  0.02996855,  0.17624883, ..., -0.29209033,
           0.04748067, -0.06

#### output of each transformer encoder layer in the BERT model. Here we have BERT base model so 12 encoder layers showing.

In [15]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

##### the last embedding of encoder_output is same as sequence output